### ISSUE TITLE
threading: logfiles of threads without content

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#39]
robot code form #38 causes empty log.xml file of threads. Files are created, but empty.

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of this issue?
thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello @test-fullautomation ,
This issue no longer be reproduced.
Thanks,
Cuong
