### ISSUE TITLE
threading: send thread notification mustn't allow to send messages to not ex. threads

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#45]
threading: send thread notification mustn't allow to send messages to not ex. threads.

Expectation:
Error-Log with list of existing threads (scope robotframework)

**Comment by milanac030988** [comment]
Fixed by https://github.com/test-fullautomation/robotframework/commit/24379a289489ae8bf321d04b72f484644ba72e3e

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
