### ISSUE TITLE
threading: "wait thread notification": contribution checker concept required

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#48]
Current `wait thread notification` implementation allows to take notifications from the queue only based on the notification name.

It need to be possible to take the payload as additional criteria.
TML contribution checker concept allows using payloads as criteria.

**Comment by test-fullautomation** [comment]
to be tested with new selftest. If successful, then close

**Comment by milanac030988** [comment]
writing selftest

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of this issue?
Thank you,
Thomas

**Comment by milanac030988** [comment]
Hello Thomas,

It was fixed by https://github.com/test-fullautomation/robotframework/pull/75 and merged.

Thanks,
Cuong
