### ISSUE TITLE
Logging: robotframeworks logging seems not be able to support long-running tests

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#53]
robotframeworks logging seems not be able to support long-running tests due to huge growing log files which are very difficult to navigate

1. analyze how logging can be improved for long-running tests by means of robotframework core features.
2. improve core for better logging.

**Comment by test-fullautomation** [comment]
Hi Holger,
yes, the is the reason for Nr. 1. 
First we need to check what RobotFramework core can do, and where are the exact limits.
Then we can see how to improve.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Step 1:
https://github.com/test-fullautomation/robotframework/pull/55

**Comment by test-fullautomation** [comment]
solved and released with version 0.10.0
