### ISSUE TITLE
threading: a robot-keyword needs possibility to block reentrance

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#62]
a robot-keyword needs possibility to block reentrance

e.g. a decorator?

Idea is to wrap thread-unsafe libraries (e.g. doip) with keywords which block in case of reentance..

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of his issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Fixed by https://github.com/test-fullautomation/robotframework/pull/86

**Comment by milanac030988** [comment]
Integrated in Robotframework AIO 0.13.0
