### ISSUE TITLE
threading: debug log file needs to log thread if threads other than "main thread" exist.

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework#63]
debug log file needs to log thread if threads other than "main thread" exist in front of logged line 
similar to TML.

`thd_name> logoutput .....`

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Fixed by https://github.com/test-fullautomation/robotframework/pull/86

**Comment by milanac030988** [comment]
Integrated in Robotframework AIO 0.13.0
