### ISSUE TITLE
No logging within FOR loops in threads

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework#80]
A '`Log`' keyword is placed within a `FOR` loop of a thread:

```
THREAD    TEST_THREAD_1     False
   FOR    ${index}    IN RANGE    0    5
      Log     I am TEST_THREAD_1
   END
END
```

In debug logfile only the start and the end of the keyword is logged, but not the message itself:

```
INFO - +------- START KEYWORD: BuiltIn.Log [ I am TEST_THREAD_1 ]
INFO - +------- END KEYWORD: BuiltIn.Log (0)
```

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
can you please look into this with high priority.
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Fixed by https://github.com/test-fullautomation/robotframework/pull/86

**Comment by milanac030988** [comment]
Integrated in Robotframework AIO 0.13.0
